import csv

# Generated by Chat-GPT and modified

def load_region_list(path):
    """Load a list of region names, one per line."""
    lines = []
    supervised = False
    with open(path) as f:
        for line in f:
            if line.rstrip():
                lines.append(line.rstrip())
                if line.rstrip().endswith("pos") or line.rstrip().endswith("neg"):
                    supervised = True
    return lines, supervised

def load_chain_scores(path):
    """
    Load the main chain score table.
    File format (tab-separated):
        region_1   region_2   score   chain_length
    Return a dictionary:
        scores[(region1, region2)] = score (float)
        scores[(region2, region1)] = score (float)   # symmetric lookup
    """
    scores = {}
    with open(path) as f:
        line_count = 0
        for line in f:
            parts = line.strip().split("\t")
            if len(parts) < 4:
                continue
            r1, r2, score_str, _ = parts
            score = float(score_str)

            # Record both directions for convenience
            scores[(r1, r2)] = score
            scores[(r2, r1)] = score

            line_count += 1
    
    return scores

def write_matrix(output_path, row_regions, col_regions, scores, supervised):
    """
    Make a matrix (row_regions x col_regions) of scores and save as CSV.
    Missing entries become 0.
    """
    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        
        # Header
        if supervised:
            writer.writerow(["non_rep_region"] + col_regions + ["acr_label"])
        else:
            writer.writerow(["non_rep_region"] + col_regions)

        # Rows
        for r in row_regions:
            row = [r]
            for c in col_regions:
                row.append(scores.get((r, c), 0))
            if supervised:
                if r[-3:] == "neg":
                    row.append(0)
                elif r[-3:] == "pos":
                    row.append(1)
                else:
                    raise Exception("Some unknown regions have ACR labels, and others do not")
            writer.writerow(row)

def chain_to_csv(chain_file, unknown_file, known_file, out_path):
    # Load files
    scores = load_chain_scores(chain_file)
    known_regions, _ = load_region_list(known_file)
    unkown_regions, supervised = load_region_list(unknown_file)
    # Produce outputs
    write_matrix(out_path, unkown_regions, known_regions, scores, supervised)